[package]
name = "screenshot-beautifier"
version = "1.0.0"
description = "Screenshot Beautifier"
authors = ["minhtrong67"]
license = "MIT"
edition = "2021"

[lib]
name = "screenshot_beautifier_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
base64 = "0.22"
