[package]
name = "calendar-app"
version = "1.0.0"
description = "A Material Design 3 desktop calendar built with Tauri 2"
authors = ["minhtrong67"]
edition = "2021"
license = "MIT"

[lib]
name = "calendar_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
